### ISSUE TITLE
Cannot render 'less than or equal to' sign to pdf

### ISSUE THREAD

**Issue by smnnlt** [arcaldwell49/cik-quarto#3]
The `≤` sign does not render to pdf for me. Neither escaping `\≤` nor raw latex `\leq` works and the .tex file seems to be fine. Maybe the font does not support the character, as I did not encounter these problems with other (more common) special characters.

**Comment by arcaldwell49** [comment]
Hi Simon, can you give me a reproducible example? This working with the template files 

`To give less than or equal to just put $\le$`

**Comment by smnnlt** [comment]
My bad, inline LaTeX `$\le$ ` works for both html and pdf.
